server:
  port: 8080
spring:
  thymeleaf:
    cache: true
dubbo:
  application:
    name: user_web
  registry:
    address: zookeeper://192.168.47.128:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3