spring:
  mail:
    protocol: smtp
    host: smtp.sina.com
    username: hdq19993156232@sina.com
    password: gqy5201314
  dubbo:
    application:
      name: senderemail
    registry:
      address: zookeeper://192.168.47.128:2181
    protocol:
      port: -1
    consumer:
      check: false
server:
  port: 9091